name: automerge

on:
  workflow_call:
    secrets:
      token:
        description: Personal Access Token that has permissions to merge pull requests
        required: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          MERGE_LABELS: automerge
          MERGE_DELETE_BRANCH: true
          MERGE_READY_STATE: clean,has_hooks
          MERGE_RETRIES: 60
          MERGE_RETRY_SLEEP: 10000
