name: update-dependencies

on:
  workflow_call:
    secrets:
      token:
        description: Personal Access Token that has permissions to push changes to a repository and to create pull requests
        required: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
      - name: Configure golang
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Update dependencies
        run: |
          go get -u -t ./...
          go mod tidy
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.token }}
          commit-message: "[CI] Update dependencies"
          branch: update-dependencies
          delete-branch: true
          title: "[CI] Update dependencies"
